services:
  - type: web
    name: vamous-clips-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: vamous
      - key: MONGODB_COLLECTION_NAME
        value: clips
      - key: DATABASE_PATH
        value: vamous_clips.db
